import { describe, it, expect, beforeEach, afterEach } from "bun:test";
import { mkdir, readFile } from "node:fs/promises";
import { join } from "node:path";

import { generate, resolveGeneratedPaths } from "./codegen";
import { makeDir, writePage, removeDir } from "./test-helpers";

// ─────────────────────────────────────────────
// codegen — generated file
// ─────────────────────────────────────────────

describe("codegen — generated file", () => {
  let pagesDir: string;
  let outDir: string;
  let root: string;

  beforeEach(async () => {
    root = await makeDir("root");
    pagesDir = join(root, "src/pages");
    outDir = join(root, "src/generated");
    await mkdir(pagesDir, { recursive: true });
  });

  afterEach(async () => {
    await removeDir(root);
  });

  async function runCodegen() {
    await generate(pagesDir, outDir);
    return readFile(resolveGeneratedPaths(outDir).serverFile, "utf8");
  }

  it("generates a file with the @generated header", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    expect(await runCodegen()).toContain("@generated by @ilha/router");
  });

  it("maps index.ts → /", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    expect(await runCodegen()).toContain(`route("/"`);
  });

  it("maps about.ts → /about", async () => {
    await writePage(pagesDir, "about.ts", `export default null;`);
    expect(await runCodegen()).toContain(`route("/about"`);
  });

  it("maps [id].ts → /:id", async () => {
    await writePage(pagesDir, "[id].ts", `export default null;`);
    expect(await runCodegen()).toContain(`route("/:id"`);
  });

  it("maps user/[id].ts → /user/:id", async () => {
    await writePage(pagesDir, "user/[id].ts", `export default null;`);
    expect(await runCodegen()).toContain(`route("/user/:id"`);
  });

  it("maps [...slug].ts → /**:slug", async () => {
    await writePage(pagesDir, "[...slug].ts", `export default null;`);
    expect(await runCodegen()).toContain(`route("/**:slug"`);
  });

  it("maps nested [org]/[repo].ts → /:org/:repo", async () => {
    await writePage(pagesDir, "[org]/[repo].ts", `export default null;`);
    expect(await runCodegen()).toContain(`route("/:org/:repo"`);
  });

  it("excludes +layout.ts and +error.ts from Page routes", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    await writePage(pagesDir, "+layout.ts", `export default null;`);
    await writePage(pagesDir, "+error.ts", `export default null;`);
    const code = await runCodegen();
    const routeLines = code.split("\n").filter((l) => l.includes(".route("));
    expect(routeLines.every((l) => !l.includes("+layout"))).toBe(true);
    expect(routeLines.every((l) => !l.includes("+error"))).toBe(true);
    expect(routeLines).toHaveLength(1);
    expect(routeLines[0]).toContain(`"/"`);
  });

  it("imports root +layout.ts and wraps Page", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    await writePage(pagesDir, "+layout.ts", `export default null;`);
    const code = await runCodegen();
    expect(code).toContain("wrapLayout(");
    expect(code).toContain("+layout.ts");
  });

  it("imports root +layout.tsx and wraps Page", async () => {
    await writePage(pagesDir, "index.tsx", `export default null;`);
    await writePage(pagesDir, "+layout.tsx", `export default null;`);
    const code = await runCodegen();
    expect(code).toContain("wrapLayout(");
    expect(code).toContain("+layout.tsx");
  });

  it("imports root +error.ts and wraps Page", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    await writePage(pagesDir, "+error.ts", `export default null;`);
    const code = await runCodegen();
    expect(code).toContain("wrapError(");
    expect(code).toContain("+error.ts");
  });

  it("imports root +error.tsx and wraps Page", async () => {
    await writePage(pagesDir, "index.tsx", `export default null;`);
    await writePage(pagesDir, "+error.tsx", `export default null;`);
    const code = await runCodegen();
    expect(code).toContain("wrapError(");
    expect(code).toContain("+error.tsx");
  });

  it("nested +layout.ts is applied only to pages in its subtree", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    await writePage(pagesDir, "user/index.ts", `export default null;`);
    await writePage(pagesDir, "+layout.ts", `export default null;`);
    await writePage(pagesDir, "user/+layout.ts", `export default null;`);
    const code = await runCodegen();
    const wrappedLines = code
      .split("\n")
      .filter((l) => l.includes("const _wrapped") && l.includes("wrapLayout"));
    const userWrapped = wrappedLines.find((l) => l.includes("_layout1"));
    const rootWrapped = wrappedLines.find((l) => l.includes("_layout0") && !l.includes("_layout1"));
    expect([...userWrapped!.matchAll(/wrapLayout/g)]).toHaveLength(2);
    expect([...rootWrapped!.matchAll(/wrapLayout/g)]).toHaveLength(1);
  });

  it("root layout wraps all pages, nested layout wraps only its subtree", async () => {
    await writePage(pagesDir, "about.ts", `export default null;`);
    await writePage(pagesDir, "user/[id].ts", `export default null;`);
    await writePage(pagesDir, "+layout.ts", `export default null;`);
    await writePage(pagesDir, "user/+layout.ts", `export default null;`);
    const code = await runCodegen();
    const wrappedLines = code
      .split("\n")
      .filter((l) => l.includes("const _wrapped") && l.includes("wrapLayout"));
    const aboutWrapped = wrappedLines.find((l) => l.includes("_page0") || l.includes("about"));
    const userWrapped = wrappedLines.find((l) => l.includes("_page1") || l.includes("user"));
    expect([...aboutWrapped!.matchAll(/wrapLayout/g)]).toHaveLength(1);
    expect([...userWrapped!.matchAll(/wrapLayout/g)]).toHaveLength(2);
  });

  it("generates export const pageRouter", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    expect(await runCodegen()).toContain("export const pageRouter");
  });

  it("defaults generated pageRouter to SPA mode", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    expect(await runCodegen()).toContain("export const pageRouter = router()");
  });

  it("can generate a no-intercept SPA pageRouter", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    await generate(pagesDir, outDir, { interceptLinks: false });
    expect(await readFile(resolveGeneratedPaths(outDir).clientFile, "utf8")).toContain(
      `export const pageRouter = router({ interceptLinks: false })`,
    );
  });

  it("does not generate export default", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    expect(await runCodegen()).not.toContain("export default");
  });

  it("empty pages dir generates an empty router", async () => {
    const code = await runCodegen();
    expect(code).toContain("export const pageRouter = router()");
    expect(code).not.toContain(".route(");
  });

  // ─────────────────────────────────────────────
  // Route groups
  // ─────────────────────────────────────────────

  it("route group: (auth)/sign-in.ts → /sign-in", async () => {
    await writePage(pagesDir, "(auth)/sign-in.ts", `export default null;`);
    expect(await runCodegen()).toContain(`route("/sign-in"`);
  });

  it("route group: (auth)/sign-up.ts → /sign-up", async () => {
    await writePage(pagesDir, "(auth)/sign-up.ts", `export default null;`);
    expect(await runCodegen()).toContain(`route("/sign-up"`);
  });

  it("route group: (marketing)/index.ts → /", async () => {
    await writePage(pagesDir, "(marketing)/index.ts", `export default null;`);
    expect(await runCodegen()).toContain(`route("/"`);
  });

  it("route group: (shop)/products/[id].ts → /products/:id", async () => {
    await writePage(pagesDir, "(shop)/products/[id].ts", `export default null;`);
    expect(await runCodegen()).toContain(`route("/products/:id"`);
  });

  it("route group folder name does not appear in the URL", async () => {
    await writePage(pagesDir, "(auth)/sign-in.ts", `export default null;`);
    const code = await runCodegen();
    expect(code).not.toContain(`"(auth)`);
    expect(code).not.toContain(`/auth/`);
  });

  it("multiple route groups can coexist without collision", async () => {
    await writePage(pagesDir, "(auth)/sign-in.ts", `export default null;`);
    await writePage(pagesDir, "(marketing)/about.ts", `export default null;`);
    const code = await runCodegen();
    expect(code).toContain(`route("/sign-in"`);
    expect(code).toContain(`route("/about"`);
  });

  it("route group +layout.ts wraps only pages inside the group", async () => {
    await writePage(pagesDir, "(auth)/sign-in.ts", `export default null;`);
    await writePage(pagesDir, "about.ts", `export default null;`);
    await writePage(pagesDir, "(auth)/+layout.ts", `export default null;`);
    const code = await runCodegen();
    const lines = code.split("\n");
    const wrappedLines = lines.filter(
      (l) => l.includes("const _wrapped") && l.includes("wrapLayout"),
    );
    // exactly one Page gets wrapped (sign-in); about does not
    expect(wrappedLines).toHaveLength(1);
    // find which _pageN import corresponds to sign-in, then verify that variable is the wrapped one
    const signInImport = lines.find((l) => l.startsWith("import") && l.includes("sign-in"));
    const PageVar = signInImport?.match(/as (_page\d+)/)?.[1];
    expect(PageVar).toBeDefined();
    expect(wrappedLines[0]).toContain(PageVar!);
  });

  it("route group +layout.ts is picked up by chainForFile for pages inside it", async () => {
    await writePage(pagesDir, "(auth)/sign-in.ts", `export default null;`);
    await writePage(pagesDir, "(auth)/+layout.ts", `export default null;`);
    const code = await runCodegen();
    expect(code).toContain("wrapLayout(");
    expect(code).toContain("+layout.ts");
  });

  it("route group +layout.tsx is picked up by chainForFile for pages inside it", async () => {
    await writePage(pagesDir, "(auth)/sign-in.tsx", `export default null;`);
    await writePage(pagesDir, "(auth)/+layout.tsx", `export default null;`);
    const code = await runCodegen();
    expect(code).toContain("wrapLayout(");
    expect(code).toContain("+layout.tsx");
  });

  it("route group +error.tsx is picked up by chainForFile for pages inside it", async () => {
    await writePage(pagesDir, "(auth)/sign-in.tsx", `export default null;`);
    await writePage(pagesDir, "(auth)/+error.tsx", `export default null;`);
    const code = await runCodegen();
    expect(code).toContain("wrapError(");
    expect(code).toContain("+error.tsx");
  });

  it("root +layout.ts also wraps pages inside a route group", async () => {
    await writePage(pagesDir, "(auth)/sign-in.ts", `export default null;`);
    await writePage(pagesDir, "+layout.ts", `export default null;`);
    const code = await runCodegen();
    expect(code).toContain("wrapLayout(");
  });

  it("nested route group: (a)/(b)/Page.ts → /Page", async () => {
    await writePage(pagesDir, "(a)/(b)/Page.ts", `export default null;`);
    expect(await runCodegen()).toContain(`route("/Page"`);
  });

  it("route group: (auth)/sign-in.ts → /sign-in", async () => {
    await writePage(pagesDir, "(auth)/sign-in.ts", `export default null;`);
    expect(await runCodegen()).toContain(`route("/sign-in"`);
  });

  it("leaf filename (landing).ts is NOT treated as a group — maps to /(landing)", async () => {
    await writePage(pagesDir, "(landing).ts", `export default null;`);
    expect(await runCodegen()).toContain(`route("/(landing)"`);
  });

  it("leaf filename (landing).ts does not collide with index.ts", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    await writePage(pagesDir, "(landing).ts", `export default null;`);
    const code = await runCodegen();
    expect(code).toContain(`route("/"`);
    expect(code).toContain(`route("/(landing)"`);
  });

  it("group folder (auth) is transparent but leaf (login).ts in it is not", async () => {
    await writePage(pagesDir, "(auth)/(login).ts", `export default null;`);
    expect(await runCodegen()).toContain(`route("/(login)"`);
  });
});

// ─────────────────────────────────────────────
// codegen — registry
// ─────────────────────────────────────────────

describe("codegen — registry", () => {
  let pagesDir: string;
  let outDir: string;
  let root: string;

  beforeEach(async () => {
    root = await makeDir("registry");
    pagesDir = join(root, "src/pages");
    outDir = join(root, ".ilha");
    await mkdir(pagesDir, { recursive: true });
  });

  afterEach(async () => {
    await removeDir(root);
  });

  async function runCodegen() {
    await generate(pagesDir, outDir);
    return readFile(resolveGeneratedPaths(outDir).serverFile, "utf8");
  }

  it("generates export const registry", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    expect(await runCodegen()).toContain("export const registry");
  });

  it("registry is typed as Record<string, Island<any, any>>", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    expect(await runCodegen()).toContain("Record<string, Island<any, any>>");
  });

  it("imports Island type from ilha", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    expect(await runCodegen()).toContain(`from "ilha"`);
  });

  it("maps index.ts → registry key 'index'", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    expect(await runCodegen()).toContain(`"index"`);
  });

  it("maps about.ts → registry key 'about'", async () => {
    await writePage(pagesDir, "about.ts", `export default null;`);
    expect(await runCodegen()).toContain(`"about"`);
  });

  it("maps [id].ts → registry key 'id'", async () => {
    await writePage(pagesDir, "[id].ts", `export default null;`);
    expect(await runCodegen()).toContain(`"id"`);
  });

  it("maps user/[id].ts → registry key 'user-id'", async () => {
    await writePage(pagesDir, "user/[id].ts", `export default null;`);
    expect(await runCodegen()).toContain(`"user-id"`);
  });

  it("maps [...slug].ts → registry key 'slug'", async () => {
    await writePage(pagesDir, "[...slug].ts", `export default null;`);
    expect(await runCodegen()).toContain(`"slug"`);
  });

  it("maps anonymous wildcard [...].ts → registry key 'wildcard'", async () => {
    // [...] — empty param name → wildcard
    await writePage(pagesDir, "[...].ts", `export default null;`);
    const code = await runCodegen();
    expect(code).toContain(`"wildcard"`);
  });

  it("registry maps to wrapped island variables (same as route) for hydration to work", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    await writePage(pagesDir, "+layout.ts", `export default null;`);
    const code = await runCodegen();
    const regBlock = code.slice(
      code.indexOf("export const registry"),
      code.indexOf("}", code.indexOf("export const registry")) + 2,
    );
    // Registry must reference the wrapped island variable so renderHydratable can find by identity
    expect(regBlock).toContain("_wrapped");
    expect(regBlock).toMatch(/"index"/);
  });

  it("registry appears before pageRouter in the file", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    const code = await runCodegen();
    expect(code.indexOf("export const registry")).toBeLessThan(
      code.indexOf("export const pageRouter"),
    );
  });

  it("empty pages dir generates an empty registry object", async () => {
    const code = await runCodegen();
    expect(code).toContain("export const registry");
    expect(code).toMatch(/export const registry[^=]*=\s*\{\s*\}/);
  });

  // Route group registry names
  it("route group: (auth)/sign-in.ts → registry key 'sign-in'", async () => {
    await writePage(pagesDir, "(auth)/sign-in.ts", `export default null;`);
    expect(await runCodegen()).toContain(`"sign-in"`);
  });

  it("route group: (shop)/products/[id].ts → registry key 'products-id'", async () => {
    await writePage(pagesDir, "(shop)/products/[id].ts", `export default null;`);
    expect(await runCodegen()).toContain(`"products-id"`);
  });
});

// ─────────────────────────────────────────────
// codegen — registry name collision detection
// ─────────────────────────────────────────────

describe("codegen — registry name collision", () => {
  let pagesDir: string;
  let outDir: string;
  let root: string;
  let warnings: string[];

  beforeEach(async () => {
    root = await makeDir("namecol");
    pagesDir = join(root, "src/pages");
    outDir = join(root, ".ilha");
    await mkdir(pagesDir, { recursive: true });
    warnings = [];
    console.warn = (...args: any[]) => warnings.push(args.join(" "));
  });

  afterEach(async () => {
    await removeDir(root);
  });

  async function runCodegen() {
    await generate(pagesDir, outDir);
    return readFile(resolveGeneratedPaths(outDir).serverFile, "utf8");
  }

  it("warns on registry name collision", async () => {
    await writePage(pagesDir, "user.ts", `export default null;`);
    await writePage(pagesDir, "user/index.ts", `export default null;`);
    await runCodegen();
    expect(warnings.some((w) => w.includes("Duplicate") || w.includes("collision"))).toBe(true);
  });

  it("does not warn on name collision when all names are unique", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    await writePage(pagesDir, "about.ts", `export default null;`);
    await runCodegen();
    expect(warnings.some((w) => w.includes("collision"))).toBe(false);
  });

  it("still generates the file when a name collision exists", async () => {
    await writePage(pagesDir, "user.ts", `export default null;`);
    await writePage(pagesDir, "user/index.ts", `export default null;`);
    const code = await runCodegen();
    expect(code).toContain("export const registry");
  });

  it("route group collision: (auth)/sign-in.ts and sign-in.ts produce same pattern — warns", async () => {
    await writePage(pagesDir, "(auth)/sign-in.ts", `export default null;`);
    await writePage(pagesDir, "sign-in.ts", `export default null;`);
    await runCodegen();
    expect(warnings.some((w) => w.includes("Duplicate") || w.includes("/sign-in"))).toBe(true);
  });
});

// ─────────────────────────────────────────────
// codegen — route sorting
// ─────────────────────────────────────────────

describe("codegen — route sorting", () => {
  let pagesDir: string;
  let outDir: string;
  let root: string;

  beforeEach(async () => {
    root = await makeDir("sort");
    pagesDir = join(root, "src/pages");
    outDir = join(root, "src/generated");
    await mkdir(pagesDir, { recursive: true });
  });

  afterEach(async () => {
    await removeDir(root);
  });

  async function runCodegen() {
    await generate(pagesDir, outDir);
    return readFile(resolveGeneratedPaths(outDir).serverFile, "utf8");
  }

  it("static routes appear before param routes", async () => {
    await writePage(pagesDir, "[id].ts", `export default null;`);
    await writePage(pagesDir, "about.ts", `export default null;`);
    const lines = (await runCodegen()).split("\n").filter((l) => l.includes(".route("));
    const aboutIdx = lines.findIndex((l) => l.includes("about"));
    const paramIdx = lines.findIndex((l) => l.includes(":id"));
    expect(aboutIdx).toBeLessThan(paramIdx);
  });

  it("param routes appear before wildcard routes", async () => {
    await writePage(pagesDir, "[...slug].ts", `export default null;`);
    await writePage(pagesDir, "[id].ts", `export default null;`);
    const lines = (await runCodegen()).split("\n").filter((l) => l.includes(".route("));
    const paramIdx = lines.findIndex((l) => l.includes(":id"));
    const wildcardIdx = lines.findIndex((l) => l.includes("**"));
    expect(paramIdx).toBeLessThan(wildcardIdx);
  });

  it("/ root route appears before all others", async () => {
    await writePage(pagesDir, "[...slug].ts", `export default null;`);
    await writePage(pagesDir, "[id].ts", `export default null;`);
    await writePage(pagesDir, "about.ts", `export default null;`);
    await writePage(pagesDir, "index.ts", `export default null;`);
    const lines = (await runCodegen()).split("\n").filter((l) => l.includes(".route("));
    expect(lines[0]).toContain(`"/"`);
  });

  it("full order: static > param > wildcard", async () => {
    await writePage(pagesDir, "[...slug].ts", `export default null;`);
    await writePage(pagesDir, "[id].ts", `export default null;`);
    await writePage(pagesDir, "about.ts", `export default null;`);
    await writePage(pagesDir, "index.ts", `export default null;`);
    const lines = (await runCodegen()).split("\n").filter((l) => l.includes(".route("));
    const order = lines.map((l) => {
      if (l.includes(`"/"`)) return "root";
      if (l.includes("about")) return "static";
      if (l.includes(":id")) return "param";
      if (l.includes("**")) return "wildcard";
      return "other";
    });
    expect(order).toEqual(["root", "static", "param", "wildcard"]);
  });

  it("route group pages sort correctly alongside non-grouped pages", async () => {
    await writePage(pagesDir, "(auth)/sign-in.ts", `export default null;`);
    await writePage(pagesDir, "(auth)/[token].ts", `export default null;`);
    await writePage(pagesDir, "about.ts", `export default null;`);
    const lines = (await runCodegen()).split("\n").filter((l) => l.includes(".route("));
    const aboutIdx = lines.findIndex((l) => l.includes("/about"));
    const signInIdx = lines.findIndex((l) => l.includes("/sign-in"));
    const tokenIdx = lines.findIndex((l) => l.includes(":token"));
    // both static routes before the param route
    expect(aboutIdx).toBeLessThan(tokenIdx);
    expect(signInIdx).toBeLessThan(tokenIdx);
  });
});

// ─────────────────────────────────────────────
// codegen — duplicate pattern detection
// ─────────────────────────────────────────────

describe("codegen — duplicate pattern detection", () => {
  let pagesDir: string;
  let outDir: string;
  let root: string;
  let warnings: string[];

  beforeEach(async () => {
    root = await makeDir("dup");
    pagesDir = join(root, "src/pages");
    outDir = join(root, "src/generated");
    await mkdir(pagesDir, { recursive: true });
    warnings = [];
    console.warn = (...args: any[]) => warnings.push(args.join(" "));
  });

  afterEach(async () => {
    await removeDir(root);
  });

  async function runCodegen() {
    await generate(pagesDir, outDir);
    return readFile(resolveGeneratedPaths(outDir).serverFile, "utf8");
  }

  it("warns when two files produce the same pattern", async () => {
    await writePage(pagesDir, "user.ts", `export default null;`);
    await writePage(pagesDir, "user/index.ts", `export default null;`);
    await runCodegen();
    expect(warnings.some((w) => w.includes("/user") && w.includes("Duplicate"))).toBe(true);
  });

  it("includes both file paths in the duplicate warning", async () => {
    await writePage(pagesDir, "user.ts", `export default null;`);
    await writePage(pagesDir, "user/index.ts", `export default null;`);
    await runCodegen();
    const warn = warnings.find((w) => w.includes("Duplicate"));
    expect(warn).toContain("user.ts");
    expect(warn).toContain("user/index.ts");
  });

  it("does not warn when all patterns are unique", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    await writePage(pagesDir, "about.ts", `export default null;`);
    await runCodegen();
    expect(warnings.some((w) => w.includes("Duplicate"))).toBe(false);
  });

  it("still generates the file when duplicates exist", async () => {
    await writePage(pagesDir, "user.ts", `export default null;`);
    await writePage(pagesDir, "user/index.ts", `export default null;`);
    expect(await runCodegen()).toContain("export const pageRouter");
  });
});

// ─────────────────────────────────────────────
// codegen — empty pages dir warning
// ─────────────────────────────────────────────

describe("codegen — empty pages dir warning", () => {
  let pagesDir: string;
  let outDir: string;
  let root: string;
  let warnings: string[];

  beforeEach(async () => {
    root = await makeDir("empty");
    pagesDir = join(root, "src/pages");
    outDir = join(root, "src/generated");
    await mkdir(pagesDir, { recursive: true });
    warnings = [];
    console.warn = (...args: any[]) => warnings.push(args.join(" "));
  });

  afterEach(async () => {
    await removeDir(root);
  });

  async function runCodegen() {
    await generate(pagesDir, outDir);
    return readFile(resolveGeneratedPaths(outDir).serverFile, "utf8");
  }

  it("warns when pages dir is empty", async () => {
    await runCodegen();
    expect(warnings.some((w) => w.includes("No pages found"))).toBe(true);
  });

  it("includes the pages dir path in the warning", async () => {
    await runCodegen();
    expect(warnings.find((w) => w.includes("No pages found"))).toContain(pagesDir);
  });

  it("does not warn when pages dir has at least one Page", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    await runCodegen();
    expect(warnings.some((w) => w.includes("No pages found"))).toBe(false);
  });

  it("does not warn when pages dir only has +layout.ts / +error.ts", async () => {
    await writePage(pagesDir, "+layout.ts", `export default null;`);
    await writePage(pagesDir, "+error.ts", `export default null;`);
    await runCodegen();
    expect(warnings.some((w) => w.includes("No pages found"))).toBe(true);
  });
});

// ─────────────────────────────────────────────
// codegen — relative imports
// ─────────────────────────────────────────────

describe("codegen — relative imports", () => {
  let pagesDir: string;
  let outDir: string;
  let root: string;

  beforeEach(async () => {
    root = await makeDir("rel");
    pagesDir = join(root, "src/pages");
    outDir = join(root, ".ilha");
    await mkdir(pagesDir, { recursive: true });
  });

  afterEach(async () => {
    await removeDir(root);
  });

  async function runCodegen() {
    await generate(pagesDir, outDir);
    return readFile(resolveGeneratedPaths(outDir).serverFile, "utf8");
  }

  it("Page imports start with . or ..", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    const importLines = (await runCodegen())
      .split("\n")
      .filter((l) => l.includes("_page") && l.startsWith("import"));
    expect(importLines.length).toBeGreaterThan(0);
    for (const line of importLines) expect(line).toMatch(/from ["']\.\.?/);
  });

  it("layout imports start with . or ..", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    await writePage(pagesDir, "+layout.ts", `export default null;`);
    const importLines = (await runCodegen())
      .split("\n")
      .filter((l) => l.includes("+layout") && l.startsWith("import"));
    expect(importLines.length).toBeGreaterThan(0);
    for (const line of importLines) expect(line).toMatch(/from ["']\.\.?/);
  });

  it("no import contains an absolute path", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    await writePage(pagesDir, "+layout.ts", `export default null;`);
    await writePage(pagesDir, "+error.ts", `export default null;`);
    const bad = (await runCodegen())
      .split("\n")
      .filter(
        (l) =>
          l.startsWith("import") &&
          (l.includes("_page") || l.includes("+layout") || l.includes("+error")),
      )
      .filter((l) => !l.includes("./") && !l.includes("../"));
    expect(bad).toHaveLength(0);
  });

  it("route group Page imports are relative (no absolute path)", async () => {
    await writePage(pagesDir, "(auth)/sign-in.ts", `export default null;`);
    const importLines = (await runCodegen())
      .split("\n")
      .filter((l) => l.includes("_page") && l.startsWith("import"));
    for (const line of importLines) expect(line).toMatch(/from ["']\.\.?/);
  });
});

// ─────────────────────────────────────────────
// codegen — loader detection & ?client suffix
// ─────────────────────────────────────────────

describe("codegen — loader detection", () => {
  let pagesDir: string;
  let outDir: string;
  let loadersFile: string;
  let root: string;

  beforeEach(async () => {
    root = await makeDir("loaders");
    pagesDir = join(root, "src/pages");
    outDir = join(root, ".ilha");
    loadersFile = join(root, ".ilha/loaders.ts");
    await mkdir(pagesDir, { recursive: true });
  });

  afterEach(async () => {
    await removeDir(root);
  });

  async function runCodegen() {
    await generate(pagesDir, outDir);
    return {
      routes: await readFile(resolveGeneratedPaths(outDir).serverFile, "utf8"),
      loaders: await readFile(loadersFile, "utf8").catch(() => ""),
    };
  }

  // ── client-safe routes file ────────────────────────────────────────────

  it("Page imports in routes.ts use the ?client suffix", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    const { routes } = await runCodegen();
    const clientCode = await readFile(resolveGeneratedPaths(outDir).clientFile, "utf8");
    const PageImport = clientCode
      .split("\n")
      .find((l) => l.startsWith("import") && l.includes("_page0"));
    expect(PageImport).toBeDefined();
    expect(PageImport!).toContain("?client");
    // server file must NOT have ?client
    const serverImport = routes
      .split("\n")
      .find((l) => l.startsWith("import") && l.includes("_page0"));
    expect(serverImport).toBeDefined();
    expect(serverImport!).not.toContain("?client");
  });

  it("layout imports in routes.ts use the ?client suffix", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    await writePage(pagesDir, "+layout.ts", `export default null;`);
    await runCodegen();
    const clientCode = await readFile(resolveGeneratedPaths(outDir).clientFile, "utf8");
    const layoutImport = clientCode
      .split("\n")
      .find((l) => l.startsWith("import") && l.includes("+layout"));
    expect(layoutImport).toBeDefined();
    expect(layoutImport!).toContain("?client");
  });

  it("error imports in routes.ts use the ?client suffix", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    await writePage(pagesDir, "+error.ts", `export default null;`);
    await runCodegen();
    const clientCode = await readFile(resolveGeneratedPaths(outDir).clientFile, "utf8");
    const errorImport = clientCode
      .split("\n")
      .find((l) => l.startsWith("import") && l.includes("+error"));
    expect(errorImport).toBeDefined();
    expect(errorImport!).toContain("?client");
  });

  it("routes.ts marks routes that have loaders without importing loader code", async () => {
    await writePage(
      pagesDir,
      "index.ts",
      `export const load = async () => ({}); export default null;`,
    );
    const { routes } = await runCodegen();
    expect(routes).toContain(`.route("/", _wrapped0).markLoader("/")`);
    expect(routes).not.toContain("attachLoader");
    expect(routes).not.toContain("composeLoaders");
    expect(routes).not.toContain("import { load");

    await writePage(pagesDir, "index.ts", `export default null;`);
    await writePage(
      pagesDir,
      "+layout.ts",
      `export const load = async () => ({}); export default null;`,
    );
    const layoutOnly = await runCodegen();
    expect(layoutOnly.routes).toContain(`.markLoader("/")`);
    expect(layoutOnly.routes).not.toContain("attachLoader");
    expect(layoutOnly.routes).not.toContain("composeLoaders");
    expect(layoutOnly.routes).not.toContain("import { load");
  });

  // ── loaders.ts — written only when needed ──────────────────────────────

  it("emits an empty loaders.ts when no Page or layout has a loader", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    await writePage(pagesDir, "about.ts", `export default null;`);
    const { loaders } = await runCodegen();
    expect(loaders).toContain("intentionally empty");
    expect(loaders).not.toContain("attachLoader");
  });

  it("emits attachLoader when a Page has a load export", async () => {
    await writePage(
      pagesDir,
      "index.ts",
      `export const load = async () => ({ x: 1 }); export default null;`,
    );
    const { loaders } = await runCodegen();
    expect(loaders).toContain(`pageRouter.attachLoader("/",`);
  });

  it("imports load from the Page module (no ?client suffix) in loaders.ts", async () => {
    await writePage(
      pagesDir,
      "index.ts",
      `export const load = async () => ({}); export default null;`,
    );
    const { loaders } = await runCodegen();
    const loadImport = loaders
      .split("\n")
      .find((l) => l.startsWith("import") && l.includes("{ load as"));
    expect(loadImport).toBeDefined();
    expect(loadImport!).not.toContain("?client");
  });

  it("detects `export async function load`", async () => {
    await writePage(
      pagesDir,
      "index.ts",
      `export async function load() { return {}; }\nexport default null;`,
    );
    const { loaders } = await runCodegen();
    expect(loaders).toContain("attachLoader");
  });

  it("detects `export function load`", async () => {
    await writePage(
      pagesDir,
      "index.ts",
      `export function load() { return {}; }\nexport default null;`,
    );
    const { loaders } = await runCodegen();
    expect(loaders).toContain("attachLoader");
  });

  it("does not treat `export const loader` as a loader", async () => {
    await writePage(
      pagesDir,
      "index.ts",
      `export const loader = "not a loader";\nexport default null;`,
    );
    const { loaders } = await runCodegen();
    expect(loaders).not.toContain("attachLoader");
  });

  it("does not treat `export const loaded` as a loader", async () => {
    await writePage(pagesDir, "index.ts", `export const loaded = true;\nexport default null;`);
    const { loaders } = await runCodegen();
    expect(loaders).not.toContain("attachLoader");
  });

  it("ignores commented-out `// export const load`", async () => {
    await writePage(
      pagesDir,
      "index.ts",
      `// export const load = () => ({});\nexport default null;`,
    );
    const { loaders } = await runCodegen();
    expect(loaders).not.toContain("attachLoader");
  });

  // ── layout loaders ─────────────────────────────────────────────────────

  it("layout's load export is attached to pages in its subtree", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    await writePage(
      pagesDir,
      "+layout.ts",
      `export const load = async () => ({ layout: true });\nexport default null;`,
    );
    const { loaders } = await runCodegen();
    expect(loaders).toContain(`pageRouter.attachLoader("/",`);
    expect(loaders).toContain("+layout.ts");
  });

  it("composeLoaders is used when Page and layout both have loaders", async () => {
    await writePage(
      pagesDir,
      "index.ts",
      `export const load = async () => ({ Page: true });\nexport default null;`,
    );
    await writePage(
      pagesDir,
      "+layout.ts",
      `export const load = async () => ({ layout: true });\nexport default null;`,
    );
    const { loaders } = await runCodegen();
    expect(loaders).toContain("composeLoaders(");
    // Layout loader appears BEFORE Page loader in the composed array (outer→inner; Page last)
    const composeCall = loaders.match(/composeLoaders\(\[([^\]]+)\]\)/)?.[1];
    expect(composeCall).toBeDefined();
    const ids = composeCall!.split(",").map((s) => s.trim());
    // Layout id contains `_l`, Page id is just `_pN`
    expect(ids[0]).toMatch(/_l\d+/);
    expect(ids[ids.length - 1]).not.toMatch(/_l\d+/);
  });

  it("no composeLoaders when only one loader in the chain", async () => {
    await writePage(
      pagesDir,
      "index.ts",
      `export const load = async () => ({}); export default null;`,
    );
    const { loaders } = await runCodegen();
    expect(loaders).not.toContain("composeLoaders");
    expect(loaders).toContain("attachLoader");
  });

  it("nested layout loader is applied only to pages in its subtree", async () => {
    await writePage(pagesDir, "about.ts", `export default null;`);
    await writePage(pagesDir, "user/index.ts", `export default null;`);
    await writePage(
      pagesDir,
      "user/+layout.ts",
      `export const load = async () => ({ inUser: true });\nexport default null;`,
    );
    const { loaders } = await runCodegen();
    // /user is attached; /about is not
    expect(loaders).toContain(`attachLoader("/user",`);
    expect(loaders).not.toContain(`attachLoader("/about",`);
  });

  it("root layout loader wraps all pages, nested layout loader wraps only its subtree", async () => {
    await writePage(pagesDir, "about.ts", `export default null;`);
    await writePage(pagesDir, "user/index.ts", `export default null;`);
    await writePage(
      pagesDir,
      "+layout.ts",
      `export const load = async () => ({ root: true });\nexport default null;`,
    );
    await writePage(
      pagesDir,
      "user/+layout.ts",
      `export const load = async () => ({ inUser: true });\nexport default null;`,
    );
    const { loaders } = await runCodegen();
    // Both routes get attachLoader calls
    const attachLines = loaders.split("\n").filter((l) => l.includes("attachLoader"));
    expect(attachLines).toHaveLength(2);
    // /user should have 2 loader ids composed; /about should have just 1
    const userLine = attachLines.find((l) => l.includes(`"/user"`));
    const aboutLine = attachLines.find((l) => l.includes(`"/about"`));
    expect(userLine).toContain("composeLoaders");
    expect(aboutLine).not.toContain("composeLoaders");
  });

  it("+error.ts loaders are ignored even if the file has `export const load`", async () => {
    // Pathological but worth defending against.
    await writePage(pagesDir, "index.ts", `export default null;`);
    await writePage(
      pagesDir,
      "+error.ts",
      `export const load = async () => ({ err: true });\nexport default null;`,
    );
    const { loaders } = await runCodegen();
    expect(loaders).not.toContain("+error.ts");
    expect(loaders).not.toContain("attachLoader");
  });
});

// ─────────────────────────────────────────────
// codegen — loaders.ts structure
// ─────────────────────────────────────────────

describe("codegen — loaders.ts file", () => {
  let pagesDir: string;
  let outDir: string;
  let loadersFile: string;
  let root: string;

  beforeEach(async () => {
    root = await makeDir("loaders-struct");
    pagesDir = join(root, "src/pages");
    outDir = join(root, ".ilha");
    loadersFile = join(root, ".ilha/loaders.ts");
    await mkdir(pagesDir, { recursive: true });
  });

  afterEach(async () => {
    await removeDir(root);
  });

  async function runCodegen() {
    await generate(pagesDir, outDir);
    return readFile(loadersFile, "utf8");
  }

  it("has the @generated header", async () => {
    await writePage(
      pagesDir,
      "index.ts",
      `export const load = async () => ({}); export default null;`,
    );
    expect(await runCodegen()).toContain("@generated by @ilha/router");
  });

  it("imports composeLoaders from @ilha/router", async () => {
    await writePage(
      pagesDir,
      "index.ts",
      `export const load = async () => ({}); export default null;`,
    );
    await writePage(
      pagesDir,
      "+layout.ts",
      `export const load = async () => ({}); export default null;`,
    );
    const loaders = await runCodegen();
    expect(loaders).toContain(`import { composeLoaders } from "@ilha/router"`);
  });

  it("imports pageRouter from the server routes file", async () => {
    await writePage(
      pagesDir,
      "index.ts",
      `export const load = async () => ({}); export default null;`,
    );
    const loaders = await runCodegen();
    expect(loaders).toContain(`import { pageRouter } from`);
    expect(loaders).toContain("pages.server");
  });

  it("all imports are relative (no absolute paths)", async () => {
    await writePage(
      pagesDir,
      "index.ts",
      `export const load = async () => ({}); export default null;`,
    );
    const code = await runCodegen();
    const importLines = code
      .split("\n")
      .filter((l) => l.startsWith("import") && !l.includes("@ilha/router"));
    for (const line of importLines) {
      expect(line).toMatch(/from ["']\.\.?/);
    }
  });

  it("emits one attachLoader per Page with loaders", async () => {
    await writePage(pagesDir, "a.ts", `export const load = async () => ({}); export default null;`);
    await writePage(pagesDir, "b.ts", `export const load = async () => ({}); export default null;`);
    await writePage(pagesDir, "c.ts", `export default null;`); // no loader
    const code = await runCodegen();
    const attaches = code.split("\n").filter((l) => l.includes("attachLoader"));
    expect(attaches).toHaveLength(2);
    expect(code).not.toContain(`"/c"`);
  });

  it("does not include export default", async () => {
    await writePage(
      pagesDir,
      "index.ts",
      `export const load = async () => ({}); export default null;`,
    );
    const code = await runCodegen();
    expect(code).not.toContain("export default");
  });

  it("writes loaders.ts to the same directory as routes.ts", async () => {
    await writePage(
      pagesDir,
      "index.ts",
      `export const load = async () => ({}); export default null;`,
    );
    await runCodegen();
    // File must exist at the expected path
    expect(readFile(loadersFile, "utf8")).resolves.toBeDefined();
  });
});

// ─────────────────────────────────────────────
// codegen — static mode
// ─────────────────────────────────────────────

describe("codegen — static mode", () => {
  let pagesDir: string;
  let outDir: string;
  let root: string;

  beforeEach(async () => {
    root = await makeDir("static");
    pagesDir = join(root, "src/pages");
    outDir = join(root, ".ilha");
    await mkdir(pagesDir, { recursive: true });
  });

  afterEach(async () => {
    await removeDir(root);
  });

  async function runStatic() {
    await generate(pagesDir, outDir, { mode: "static" });
    return readFile(resolveGeneratedPaths(outDir).clientFile, "utf8");
  }

  it("emits static mode router stub", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    const code = await runStatic();
    expect(code).toContain(`router({ mode: "static" })`);
  });

  it("does not emit .route() calls", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    await writePage(pagesDir, "about.ts", `export default null;`);
    const code = await runStatic();
    expect(code).not.toContain(".route(");
  });

  it("does not emit wrapLayout even when layouts exist", async () => {
    await writePage(pagesDir, "+layout.ts", `export default null;`);
    await writePage(pagesDir, "index.ts", `export default null;`);
    const code = await runStatic();
    expect(code).not.toContain("wrapLayout");
  });

  it("does not emit wrapError even when error boundaries exist", async () => {
    await writePage(pagesDir, "+error.ts", `export default null;`);
    await writePage(pagesDir, "index.ts", `export default null;`);
    const code = await runStatic();
    expect(code).not.toContain("wrapError");
  });

  it("still exports registry with all pages", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    await writePage(pagesDir, "about.ts", `export default null;`);
    const code = await runStatic();
    expect(code).toContain("export const registry");
    expect(code).toContain('"index"');
    expect(code).toContain('"about"');
  });

  it("does not import router runtime (wrapLayout/wrapError) from @ilha/router in island imports", async () => {
    await writePage(pagesDir, "+layout.ts", `export default null;`);
    await writePage(pagesDir, "index.ts", `export default null;`);
    const code = await runStatic();
    // The only @ilha/router import should be the router stub, not wrapLayout/wrapError
    const routerImports = code.split("\n").filter((l) => l.includes(`from "@ilha/router"`));
    expect(routerImports).toHaveLength(1);
    expect(routerImports[0]).toContain("router as _router");
    expect(routerImports[0]).not.toContain("wrapLayout");
  });

  it("layout page modules are NOT imported in static mode", async () => {
    await writePage(pagesDir, "+layout.ts", `export default null;`);
    await writePage(pagesDir, "index.ts", `export default null;`);
    const code = await runStatic();
    expect(code).not.toContain("+layout.ts");
  });

  it("page with load export does not wire loader code in static mode", async () => {
    await writePage(
      pagesDir,
      "index.ts",
      `export const load = async () => null; export default null;`,
    );
    const code = await runStatic();
    expect(code).not.toContain(".route(");
    expect(code).not.toContain("load");
    expect(code).not.toContain("attachLoader");
  });
});

// ─────────────────────────────────────────────
// codegen — server/client split correctness
// ─────────────────────────────────────────────

describe("codegen — server/client split", () => {
  let pagesDir: string;
  let outDir: string;
  let root: string;

  beforeEach(async () => {
    root = await makeDir("split");
    pagesDir = join(root, "src/pages");
    outDir = join(root, ".ilha");
    await mkdir(pagesDir, { recursive: true });
  });

  afterEach(async () => {
    await removeDir(root);
  });

  it("server file does not contain ?client imports", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    await writePage(pagesDir, "+layout.ts", `export default null;`);
    await generate(pagesDir, outDir);
    const server = await readFile(resolveGeneratedPaths(outDir).serverFile, "utf8");
    expect(server).not.toContain("?client");
  });

  it("client file uses ?client imports for all page/layout/error modules", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    await writePage(pagesDir, "+layout.ts", `export default null;`);
    await writePage(pagesDir, "+error.ts", `export default null;`);
    await generate(pagesDir, outDir);
    const client = await readFile(resolveGeneratedPaths(outDir).clientFile, "utf8");
    const importLines = client
      .split("\n")
      .filter((l) => l.startsWith("import") && l.includes("src/pages"));
    expect(importLines.length).toBeGreaterThan(0);
    expect(importLines.every((l) => l.includes("?client"))).toBe(true);
  });

  it("server file has full route graph (wrapLayout, .route calls)", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    await writePage(pagesDir, "+layout.ts", `export default null;`);
    await generate(pagesDir, outDir);
    const server = await readFile(resolveGeneratedPaths(outDir).serverFile, "utf8");
    expect(server).toContain("wrapLayout");
    expect(server).toContain(".route(");
  });

  it("static mode: client file has no route graph, server file still has full graph", async () => {
    await writePage(pagesDir, "index.ts", `export default null;`);
    await writePage(pagesDir, "+layout.ts", `export default null;`);
    await generate(pagesDir, outDir, { mode: "static" });
    const client = await readFile(resolveGeneratedPaths(outDir).clientFile, "utf8");
    const server = await readFile(resolveGeneratedPaths(outDir).serverFile, "utf8");
    expect(client).not.toContain(".route(");
    expect(client).not.toContain("wrapLayout");
    expect(server).toContain(".route(");
    expect(server).toContain("wrapLayout");
  });

  it("loaders.ts imports pageRouter from pages.server, not pages.client", async () => {
    await writePage(
      pagesDir,
      "index.ts",
      `export const load = async () => ({}); export default null;`,
    );
    await generate(pagesDir, outDir);
    const loaders = await readFile(resolveGeneratedPaths(outDir).loadersFile, "utf8");
    expect(loaders).toContain("pages.server");
    expect(loaders).not.toContain("pages.client");
  });
});
