/**
 * Writes `src/lib/landing-code-html.ts` with Shiki HTML for landing tabs.
 * Run via `bun run generate:landing-code` (also predev / prebuild).
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { createHighlighter } from "shiki";

import {
  LANDING_HIGHLIGHT_THEMES,
  landingHighlightSnippets,
} from "../src/lib/landing-highlight-snippets.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outFile = join(root, "src/lib/landing-code-html.ts");

const langs = [...new Set(Object.values(landingHighlightSnippets).map((s) => s.lang))];
const themes = [...new Set(Object.values(LANDING_HIGHLIGHT_THEMES))];

const highlighter = await createHighlighter({ themes, langs });

const wrapperClass =
  "max-w-full overflow-x-auto rounded-xl border border-areia-border text-xs leading-relaxed [&_pre]:min-w-max [&_pre]:p-4 [&_pre]:text-xs [&_pre]:leading-relaxed [&_pre]:!m-0";

const entries: string[] = [];
for (const [id, { lang, code }] of Object.entries(landingHighlightSnippets)) {
  const inner = highlighter.codeToHtml(code, {
    lang,
    themes: {
      light: LANDING_HIGHLIGHT_THEMES.light,
      dark: LANDING_HIGHLIGHT_THEMES.dark,
    },
  });
  const html = `<div class="${wrapperClass}" data-landing-code>${inner}</div>`;
  entries.push(`  ${id}: ${JSON.stringify(html)},`);
}

const source = `// @generated by scripts/generate-landing-code-html.ts — do not edit

export const landingCodeHtml = {
${entries.join("\n")}
} as const;

export type LandingCodeHtmlId = keyof typeof landingCodeHtml;
`;

await mkdir(dirname(outFile), { recursive: true });
await writeFile(outFile, source, "utf8");
console.log(`wrote ${outFile}`);
